#!/usr/bin/env python3
"""
00_init_project.py — Empirical Paper Project Scaffolder

Creates a new project directory with the standard structure:
  Data/, Program/, Results/, Manuscripts/, Submissions/,
  Reference/, artifacts/, tables/, figures/, workflows/, runtime/

Usage:
  python3 scripts/00_init_project.py --topic "研究题目" --data data.csv
  python3 scripts/00_init_project.py                    # interactive mode
"""

import argparse
import os
import shutil
import sys
from pathlib import Path

TEMPLATE_DIR = Path(__file__).resolve().parent.parent  # 实证论文项目模板/

# ── Defaults ─────────────────────────────────────────────────────────────────

DEFAULT_IDENTIFICATION = {
    "did":   ("did",   ["平行趋势假设", "SUTVA"]),
    "iv":    ("iv",    ["排他性约束", "相关性（第一阶段显著）"]),
    "rdd":   ("rdd",   ["连续性假设", "带宽选择稳健"]),
    "psm":   ("psm",   ["共同支撑假设", "条件独立假设"]),
    "dml":   ("dml",   ["嵌套正交性", "正则化参数选择"]),
    "panel": ("panel", ["严格外生", "无序列相关"]),
}

DEFAULT_OUTCOME_NAME   = "ln_expense"
DEFAULT_OUTCOME_DESC   = "因变量描述：请替换为你的变量说明"
DEFAULT_OUTCOME_SOURCE = "数据来源：请替换"

DEFAULT_TREATMENT_NAME   = "high_minwage_growth"
DEFAULT_TREATMENT_DESC   = "处理变量描述：请替换为你的变量说明"
DEFAULT_TREATMENT_SOURCE = "数据来源：请替换"

DEFAULT_COVARIATES   = ["age", "gender", "familysize"]
DEFAULT_CLUSTER      = ["province_code"]
DEFAULT_PRE          = [2018]
DEFAULT_POST         = [2022]
DEFAULT_N_EXPECTED   = 60000


# ── Helpers ───────────────────────────────────────────────────────────────────

def slugify(text: str) -> str:
    """Turn '研究题目' into 'research-title'."""
    import re
    s = text.strip().lower()
    # keep ascii + cjk, replace spaces/runs with hyphen
    s = re.sub(r'[^\w一-鿿]+', '-', s)
    s = re.sub(r'-{2,}', '-', s).strip('-')
    return s or "project"


def prompt(msg: str, default: str) -> str:
    val = input(f"{msg} [{default}]: ").strip()
    return val if val else default


def write_placeholder(path: Path, comment: str = "TODO") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(f"# {comment}: fill in this file\n")


# ── causal_question.yaml ──────────────────────────────────────────────────────

def build_causal_question_yaml(topic: str, data_path: str, method: str) -> str:
    method_label, assumptions = DEFAULT_IDENTIFICATION.get(
        method, (method, ["请补充识别假设"])
    )
    return f"""# research_question: {topic}
# Auto-generated by 00_init_project.py — fill in all TODO fields.

research_question:
  title: "{topic}"
  description: "一句话描述研究问题"

  outcome:
    name: "{DEFAULT_OUTCOME_NAME}"
    description: "{DEFAULT_OUTCOME_DESC}"
    source: "{DEFAULT_OUTCOME_SOURCE}"

  treatment:
    name: "{DEFAULT_TREATMENT_NAME}"
    description: "{DEFAULT_TREATMENT_DESC}"
    source: "{DEFAULT_TREATMENT_SOURCE}"

  identification:
    method: "{method_label}"
    assumptions:
""" + "\n".join(f'      - "{a}"' for a in assumptions) + f"""

  time:
    pre: {DEFAULT_PRE}
    post: {DEFAULT_POST}

  covariates:
""" + "\n".join(f'    - {v}' for v in DEFAULT_COVARIATES) + f"""

  cluster:
""" + "\n".join(f'    - {c}' for c in DEFAULT_CLUSTER) + f"""

  sample:
    source: "Data/Raw/{Path(data_path).name}"
    n_expected: {DEFAULT_N_EXPECTED}
"""


# ── README.md ─────────────────────────────────────────────────────────────────

def build_readme(topic: str, data_path: str, method: str, project_dir: Path) -> str:
    method_label = DEFAULT_IDENTIFICATION.get(method, (method, []))[0]
    return f"""# {topic}

> {method_label.upper()} 实证项目 — auto-generated scaffold

## 目录结构

```
├── Data/
│   ├── Raw/          ← 原始数据（{Path(data_path).name}）
│   ├── Interim/      ← 中间数据
│   └── Final/        ← 分析就绪数据集
├── Program/
│   ├── Clean/        ← 清洗脚本
│   └── Analysis/     ← 分析脚本
├── Results/
│   ├── tab/          ← 输出表格（.tex / .csv）
│   └── fig/          ← 输出图表（.pdf / .png）
├── Manuscripts/
│   ├── sections/     ← 各章节 .md
│   └── generated/    ← 编译输出
├── Submissions/      ← 投稿包
├── Reference/        ← 参考文献
├── artifacts/        ← pipeline 产物
├── tables/           ← 主表格
├── figures/          ← 主图表
├── workflows/        ← workflow 注册表（从模板复制）
├── runtime/          ← pipeline engine（从模板复制）
├── causal_question.yaml   ← 研究设计规范
└── run_paper.py      ← 入口脚本
```

## 快速开始

1. 把原始数据放入 `Data/Raw/`
2. 编辑 `causal_question.yaml` 替换 TODO
3. 写清洗脚本 → `Program/Clean/`
4. 写分析脚本 → `Program/Analysis/`
5. 运行 `python3 run_paper.py`

## 识别方法

当前设定：**{method_label.upper()}**
详见 `causal_question.yaml`
"""


# ── run_paper.py ─────────────────────────────────────────────────────────────

def build_run_paper(topic: str) -> str:
    return f'''#!/usr/bin/env python3
"""
{ topic } — 主入口

按顺序执行:
  1. 清洗 (Program/Clean/)
  2. 分析 (Program/Analysis/)
  3. 生成表格 (Results/tab/)
  4. 生成图表 (Results/fig/)
"""

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent


def run_step(name: str, script: str) -> bool:
    path = PROJECT_ROOT / "Program" / name / script
    if not path.exists():
        print(f"[SKIP] {{path}} not found")
        return True
    print(f"[RUN] {{name}}/{{script}}")
    result = subprocess.run([sys.executable, str(path)], cwd=PROJECT_ROOT)
    return result.returncode == 0


def main() -> None:
    steps = [
        ("Clean",    "clean_data.py"),      # TODO: rename to match your script
        ("Analysis", "main_analysis.py"),   # TODO: rename to match your script
    ]
    for folder, script in steps:
        ok = run_step(folder, script)
        if not ok:
            print(f"[FAIL] {{folder}}/{{script}} failed — stopping.")
            sys.exit(1)
    print("[DONE] All steps passed.")


if __name__ == "__main__":
    main()
'''


# ── Placeholder files ─────────────────────────────────────────────────────────

PLACEHOLDERS = {
    "Program/Clean/clean_data.py":           "# TODO: write data cleaning script\n",
    "Program/Analysis/main_analysis.py":     "# TODO: write main analysis script\n",
    "Manuscripts/sections/introduction.md":  "# TODO: Introduction\n",
    "Manuscripts/sections/literature-and-contribution.md": "# TODO: Literature Review\n",
    "Manuscripts/sections/empirical-strategy.md": "# TODO: Empirical Strategy\n",
    "Manuscripts/sections/data-and-measurement.md": "# TODO: Data and Measurement\n",
    "Manuscripts/sections/main-results.md":  "# TODO: Main Results\n",
    "Manuscripts/sections/robustness-mechanisms-heterogeneity.md": "# TODO: Robustness\n",
    "Manuscripts/sections/conclusion.md":    "# TODO: Conclusion\n",
    "Submissions/submission_checklist.md":   "# TODO: Submission checklist\n",
    "Reference/README.md":                   "# Put .bib, .pdf, notes here\n",
    "artifacts/README.md":                   "# Pipeline artifacts (data contracts, logs, reports)\n",
}


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Scaffold a new empirical paper project."
    )
    parser.add_argument("--topic", help="研究题目")
    parser.add_argument("--data",  help="原始数据文件路径（可选，用于记录在 causal_question.yaml 中）")
    parser.add_argument("--method", default="did",
                        choices=list(DEFAULT_IDENTIFICATION.keys()),
                        help="识别方法 (默认: did)")
    parser.add_argument("--out", help="项目根目录（默认: 当前目录/<slugified-topic>）")
    args = parser.parse_args()

    # ── Resolve inputs ────────────────────────────────────────────────────────
    if args.topic:
        topic  = args.topic
        data   = args.data or "data.csv"
        method = args.method
    else:
        print("── 新项目初始化 ──")
        topic  = prompt("研究题目", "我的研究题目")
        data   = prompt("原始数据文件路径", "data/Raw/data.csv")
        method = prompt("识别方法 (did/iv/rdd/psm/dml/panel)", "did")

    slug  = slugify(topic)
    out   = Path(args.out) if args.out else Path.cwd() / slug
    out.mkdir(parents=True, exist_ok=True)

    if out.exists() and any(out.iterdir()) and not args.out:
        # only warn in non-scripted mode
        if args.topic:
            print(f"[INFO] Target {out} already exists, merging.")
        else:
            confirm = input(f"\n⚠️  {out} 已存在且非空，继续会合并内容。确认？[y/N] ").strip().lower()
            if confirm != "y":
                print("已取消。")
                sys.exit(0)

    print(f"\n📁 创建项目: {out}\n")

    # ── Directories ───────────────────────────────────────────────────────────
    dirs = [
        "Data/Raw", "Data/Interim", "Data/Final",
        "Program/Clean", "Program/Analysis",
        "Results/tab", "Results/fig",
        "Manuscripts/generated", "Manuscripts/sections",
        "Submissions",
        "Reference",
        "artifacts",
        "tables", "figures",
    ]
    for d in dirs:
        (out / d).mkdir(parents=True, exist_ok=True)
        print(f"  mkdir {d}/")

    # ── Copy runtime/ and workflows/ ──────────────────────────────────────────
    for src_name in ("runtime", "workflows"):
        src  = TEMPLATE_DIR / src_name
        dst  = out   / src_name
        if src.exists():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"))
            print(f"  copy {src_name}/  ({len(list(dst.rglob('*')))} files)")
        else:
            print(f"  [WARN] {src} not found, skipping copy")

    # ── causal_question.yaml ──────────────────────────────────────────────────
    yaml_path = out / "causal_question.yaml"
    yaml_path.write_text(build_causal_question_yaml(topic, data, method))
    print(f"  write causal_question.yaml")

    # ── README.md ─────────────────────────────────────────────────────────────
    readme_path = out / "README.md"
    readme_path.write_text(build_readme(topic, data, method, out))
    print(f"  write README.md")

    # ── run_paper.py ──────────────────────────────────────────────────────────
    entry = out / "run_paper.py"
    entry.write_text(build_run_paper(topic))
    entry.chmod(0o755)
    print(f"  write run_paper.py")

    # ── Placeholder files ─────────────────────────────────────────────────────
    for rel, content in PLACEHOLDERS.items():
        p = out / rel
        write_placeholder(p)
        if content:
            p.write_text(content)
            print(f"  write {rel}")

    # ── .gitignore (basic) ────────────────────────────────────────────────────
    gi = out / ".gitignore"
    if not gi.exists():
        gi.write_text(
            "__pycache__/\n*.pyc\n.env\nartifacts/\nData/Raw/\nResults/\ntables/\nfigures/\n"
        )
        print("  write .gitignore")

    # ── Summary ───────────────────────────────────────────────────────────────
    file_count = sum(1 for f in out.rglob("*") if f.is_file())
    print(f"\n✅  项目已创建: {out}")
    print(f"    文件数: {file_count}")
    print(f"    目录: {', '.join(dirs)}")

    print("""
─── 下一步 ───────────────────────────────────────────────

1.  cd {project}
2.  把原始数据放入 Data/Raw/{data_file}
3.  编辑 causal_question.yaml  — 替换所有 TODO
4.  写清洗脚本: Program/Clean/clean_data.py
5.  写分析脚本: Program/Analysis/main_analysis.py
6.  运行: python3 run_paper.py

识别方法: {method_label}
研究题目: {topic}
───────────────────────────────────────────────────────────
""".format(
        project=out, data_file=Path(data).name,
        method_label=DEFAULT_IDENTIFICATION.get(method, (method, []))[0],
        topic=topic,
    ))


if __name__ == "__main__":
    main()
